### ISSUE TITLE
Cannot compile namespaces when the '--isolatedModules' flag is provided

### ISSUE THREAD

**Issue by oniyakun** [Jack-Works/Sync-watch#1]
Im clone this code, edited servers.js and run
```
yarn
yarn build
```
but yarn build failed.
![z f9_ y 4c2r6 rd gbk9r](https://user-images.githubusercontent.com/30280837/52707592-01fd0c80-2fc3-11e9-97fc-4d812f948407.png)
Here is screenshot.

I can't understand what this means. Please help me

**Comment by Jack-Works** [comment]
Hmm this file should not be included in the `yarn build`. It's loaded by <script>. Let me see

**Comment by Jack-Works** [comment]
Fixed. Thanks for the report.
