### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by oniyakun** [Jack-Works/Sync-watch#2]
I deployed the project correctly and it looks worked fine, but its not sync video
I checked the Devtools console and found some problems, here is

![image](https://user-images.githubusercontent.com/30280837/52736364-a8b5cd00-3004-11e9-9f6f-98895b36ecee.png)
_It shows when I drag the bar how it works on **your instance**_

![image](https://user-images.githubusercontent.com/30280837/52736594-28dc3280-3005-11e9-93d3-f31121585b50.png)
_It shows when I drag the bar how it works on **my instance**_

There is **no any timestamp or control log** on my instance, I am try to figure this out for a night but still don't know why, please help me to fix it

Best regards

**Comment by Jack-Works** [comment]
Are you using tools like uBlock? It will block websocket to our public server

**Comment by Jack-Works** [comment]
If so, you can set up your own server by https://github.com/Jack-Works/sync-watch-server, or add an exception in the uBlock

**Comment by oniyakun** [comment]
> Are you using tools like uBlock? It will block websocket to our public server

I've disabled all adblock like uBlock, but it still doesn't work.

**Comment by oniyakun** [comment]
I'm testing the project in visitor mode, and it won't have any chrome extensions, thats the problem is: it looks websocket worked fine but it not use `src\Comps\MainComps\MediaPlayer.tsx` correctly or others wrong.

**Comment by Jack-Works** [comment]
Ok Maybe changes for the extension breaks the standalone mode. I'll take a look

**Comment by oniyakun** [comment]
> Ok Maybe changes for the extension breaks the standalone mode. I'll take a look

Got it, thanks a lot
